version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
